### ISSUE TITLE
`UnboundLocalError: local variable 'idx' referenced before assignment` 

### ISSUE THREAD

**Issue by xenova** [inisis/OnnxSlim#10]
When running
```
onnxslim test.onnx slimmed.onnx
```
on this file: [test.zip](https://github.com/user-attachments/files/15897738/test.zip)

I get the following error:

```py
Traceback (most recent call last):
  File "/usr/local/bin/onnxslim", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/onnxslim/cli/_main.py", line 271, in main
    slim(
  File "/usr/local/lib/python3.10/dist-packages/onnxslim/cli/_main.py", line 128, in slim
    model = optimize(model, skip_fusion_patterns)
  File "/usr/local/lib/python3.10/dist-packages/onnxslim/core/slim.py", line 111, in optimize
    model = optimize_model(graph, skip_fusion_patterns)
  File "/usr/local/lib/python3.10/dist-packages/onnxslim/core/optimizer.py", line 857, in optimize_model
    graph_constant_fold_inplace(graph)
  File "/usr/local/lib/python3.10/dist-packages/onnxslim/core/optimizer.py", line 164, in graph_constant_fold_inplace
    idx = 0 if idx == 1 else 1
UnboundLocalError: local variable 'idx' referenced before assignment
```

stemming from [this line of code](https://github.com/inisis/OnnxSlim/blob/b7100a6e1af622f81016fdffd98c6294d77e575a/onnxslim/core/optimizer.py#L161).

**Comment by inisis** [comment]
I'm so sorry for that, you can remove line 161 and set idx to 1, I will sovle it soon, btw, your onnx mode seems invalid, it doesn't have weight.

**Comment by inisis** [comment]
> @inisis Right - the actual model is too large, so I save the graph and weights separately. Luckily onnxslim only needs the graph to work.
> 
> ```python
> import onnx
> m = onnx.load('original.onnx')
> onnx.save(m, 'small.onnx', save_as_external_data=True)
> ```

@xenova so what does the output looks like after this modification

**Comment by xenova** [comment]
I did this:
1. Generate large .onnx file (e.g., `large_model.onnx`)
2. Save model and graph separately
```py
import onnx
m = onnx.load('large_model.onnx')
onnx.save(m, 'model.onnx', save_as_external_data=True)
```
3. Run onnxslim and overwrite original `model.onnx`: `onnxslim model.onnx model.onnx`
4. Run the model normally

This works :)

**Comment by inisis** [comment]
> I did this:
> 
> 1. Generate large .onnx file (e.g., `large_model.onnx`)
> 2. Save model and graph separately
> 
> ```python
> import onnx
> m = onnx.load('large_model.onnx')
> onnx.save(m, 'model.onnx', save_as_external_data=True)
> ```
> 
> 3. Run onnxslim and overwrite original `model.onnx`: `onnxslim model.onnx model.onnx`
> 4. Run the model normally
> 
> This works :)

That's greate. Onnxslim will automatically save your onnx into graph and weight separately.
