### ISSUE TITLE
No module named packaging

### ISSUE THREAD

**Issue by glenn-jocher** [inisis/OnnxSlim#4]
If I install simpy to resolve #3 I get a new error:

```
onnxslim OnnxSlim yolov8n.onnx

Traceback (most recent call last):
  File "/Users/glennjocher/PycharmProjects/OnnxSlim/venv/bin/onnxslim", line 33, in <module>
    sys.exit(load_entry_point('onnxslim', 'console_scripts', 'onnxslim')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennjocher/PycharmProjects/OnnxSlim/onnxslim/cli/_main.py", line 281, in main
    slim(
  File "/Users/glennjocher/PycharmProjects/OnnxSlim/onnxslim/cli/_main.py", line 62, in slim
    from onnxslim.core.slim import (
  File "/Users/glennjocher/PycharmProjects/OnnxSlim/onnxslim/core/slim.py", line 23, in <module>
    from .symbolic_shape_infer import SymbolicShapeInference
  File "/Users/glennjocher/PycharmProjects/OnnxSlim/onnxslim/core/symbolic_shape_infer.py", line 12, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

**Comment by inisis** [comment]
Hi, @glenn-jocher, the correct usage should be onnxslim yolov8n.onnx slim.onnx, and I should add a onnxruntime dependecy.

**Comment by inisis** [comment]
@glenn-jocher Hi, can you add me to the Ultralytics Actions group, I can not perform Ultralytics Formatting right now.
![image](https://github.com/inisis/OnnxSlim/assets/46103969/c18b4f77-d3af-4993-a4e6-a5dfe6856df2)
